"use client";

import * as React from "react";
import { ArrowRight, Images, Loader2, ChevronLeft, ChevronRight, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { SectionHeader } from "./section-header";
import { PYCButton } from "./button";
// Auto-generated by `bun run scripts/scan-gallery.js`
// Falls back to the default Unsplash collection if no local images are uploaded.
import localImages from "@/data/gallery-images";

export const CATEGORIES = [
  "All",
  "Community",
  "Education",
  "Health",
  "Environment",
  "Events",
] as const;
export type Category = typeof CATEGORIES[number];

export interface GalleryImage {
  src: string;
  alt: string;
  category: Exclude<Category, "All">;
  span?: boolean;
}

// Default placeholder collection (used when public/gallery/ is empty).
// Once you drop photos into public/gallery/<category>/ and run
// `bun run scripts/scan-gallery.js`, the local manifest takes over.
const DEFAULT_IMAGES: GalleryImage[] = [
  {
    src: "https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=800&q=80",
    alt: "Volunteers helping children in a rural community",
    category: "Community",
    span: true,
  },
  {
    src: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=600&q=80",
    alt: "Classroom learning session",
    category: "Education",
  },
  {
    src: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=600&q=80",
    alt: "Health outreach camp",
    category: "Health",
  },
  {
    src: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?auto=format&fit=crop&w=600&q=80",
    alt: "Tree planting activity",
    category: "Environment",
  },
  {
    src: "https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=800&q=80",
    alt: "Youth summit event",
    category: "Events",
    span: true,
  },
  {
    src: "https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=600&q=80",
    alt: "Children at a community library",
    category: "Education",
  },
  {
    src: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?auto=format&fit=crop&w=600&q=80",
    alt: "Volunteers distributing supplies",
    category: "Community",
  },
  {
    src: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=600&q=80",
    alt: "Health education workshop",
    category: "Health",
  },
  {
    src: "https://images.unsplash.com/photo-1518621736915-f3b1c41bfd00?auto=format&fit=crop&w=600&q=80",
    alt: "Reforestation campaign",
    category: "Environment",
  },
  {
    src: "https://images.unsplash.com/photo-1529390079861-591de354faf5?auto=format&fit=crop&w=600&q=80",
    alt: "Annual gala event",
    category: "Events",
  },
];

// Use local images if the manifest has any, otherwise fall back to defaults.
const STATIC_IMAGES: GalleryImage[] =
  Array.isArray(localImages) && localImages.length > 0
    ? (localImages as GalleryImage[])
    : DEFAULT_IMAGES;

interface GalleryProps {
  /** Limit the number of images shown (home page uses 6). */
  limit?: number;
  /** Show the "View Full Gallery" button (home page uses true). */
  showViewMore?: boolean;
  /** Number of images to load per "page" when paginating (default: 12). */
  pageSize?: number;
}

export function Gallery({ limit, showViewMore = false, pageSize = 12 }: GalleryProps = {}) {
  const [filter, setFilter] = React.useState<Category>("All");
  const [visibleCount, setVisibleCount] = React.useState(pageSize);
  // Fetch the latest image count from the API (for dynamic uploads)
  const [dynamicTotal, setDynamicTotal] = React.useState<number | null>(null);
  // Lightbox state
  const [lightboxIndex, setLightboxIndex] = React.useState<number | null>(null);

  React.useEffect(() => {
    // Check if we're on the full gallery page (not the home preview)
    if (typeof limit === "number") return;
    fetch("/api/upload")
      .then((res) => res.ok ? res.json() : null)
      .then((data) => {
        if (data?.total && data.total !== STATIC_IMAGES.length) {
          setDynamicTotal(data.total);
        }
      })
      .catch(() => {});
  }, [limit]);

  const isLimited = typeof limit === "number";

  // Reset pagination when filter changes
  React.useEffect(() => {
    setVisibleCount(pageSize);
  }, [filter, pageSize]);

  // For limited (home) view: no filter, just take the first `limit` images
  const filtered = isLimited
    ? STATIC_IMAGES.slice(0, limit)
    : filter === "All"
      ? STATIC_IMAGES
      : STATIC_IMAGES.filter((img) => img.category === filter);

  // Apply pagination to the full gallery view
  const displayed = isLimited ? filtered : filtered.slice(0, visibleCount);
  const hasMore = !isLimited && visibleCount < filtered.length;
  const remainingCount = filtered.length - visibleCount;

  // Keyboard navigation for lightbox
  React.useEffect(() => {
    if (lightboxIndex === null) return;

    const handleKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        setLightboxIndex(null);
      } else if (e.key === "ArrowRight") {
        e.preventDefault();
        setLightboxIndex((prev) =>
          prev !== null ? (prev + 1) % displayed.length : null
        );
      } else if (e.key === "ArrowLeft") {
        e.preventDefault();
        setLightboxIndex((prev) =>
          prev !== null
            ? (prev - 1 + displayed.length) % displayed.length
            : null
        );
      }
    };

    window.addEventListener("keydown", handleKey);
    // Prevent body scroll when lightbox is open
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", handleKey);
      document.body.style.overflow = "";
    };
  }, [lightboxIndex, displayed.length]);

  return (
    <section id="gallery" className="relative bg-white py-20 md:py-28">
      <div className="section-pad">
        <SectionHeader
          eyebrow="Gallery"
          title={
            <>
              Moments of <span className="text-brand">hope in action</span>
            </>
          }
          description="A glimpse into the people, places, and partnerships that make PYC Club's work possible across the Volta Region."
        />

        {/* New uploads banner — shows when API detects more images than the build-time manifest */}
        {!isLimited && dynamicTotal !== null && dynamicTotal > STATIC_IMAGES.length && (
          <div className="reveal mt-6 mx-auto max-w-2xl rounded-2xl bg-brand-gradient-soft border border-brand/15 p-4 text-center">
            <p className="text-sm text-[#0E1530]">
              <strong>{dynamicTotal - STATIC_IMAGES.length} new image{dynamicTotal - STATIC_IMAGES.length === 1 ? "" : "s"}</strong> uploaded recently.
              {" "}
              <button
                onClick={() => window.location.reload()}
                className="text-brand font-semibold underline hover:text-brand-deep"
              >
                Refresh page
              </button>
              {" "}to see them, or{" "}
              <a href="/media" className="text-brand font-semibold underline hover:text-brand-deep">
                upload more
              </a>.
            </p>
          </div>
        )}

        {/* Filter pills — only on full gallery page */}
        {!isLimited && (
          <div className="reveal mt-10 flex flex-wrap justify-center gap-2">
            {CATEGORIES.map((c) => (
              <button
                key={c}
                onClick={() => setFilter(c)}
                aria-pressed={filter === c}
                className={cn(
                  "rounded-full px-5 py-2 text-sm font-semibold transition-all",
                  filter === c
                    ? "bg-brand text-white shadow-premium"
                    : "bg-surface text-[#5A6485] hover:bg-brand-soft/10 hover:text-brand"
                )}
              >
                {c}
              </button>
            ))}
          </div>
        )}

        {/* Masonry grid */}
        <div className="mt-10 columns-1 gap-4 sm:columns-2 lg:columns-3 [&>*]:mb-4">
          {displayed.map((img, i) => (
            <figure
              key={`${img.src}-${i}`}
              onClick={() => setLightboxIndex(i)}
              className={cn(
                "reveal group relative overflow-hidden rounded-3xl shadow-premium break-inside-avoid cursor-pointer",
                img.span ? "aspect-[4/5]" : "aspect-square"
              )}
              style={{ transitionDelay: `${(i % 6) * 0.05}s` }}
            >
              <img
                src={img.src}
                alt={img.alt}
                className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-110"
                loading="lazy"
              />
              <div
                aria-hidden
                className="absolute inset-0 bg-gradient-to-t from-[#0B1130]/40 via-transparent to-transparent opacity-0 transition-opacity group-hover:opacity-100"
              />
            </figure>
          ))}
        </div>

        {/* View Full Gallery button — only on home page (limited view) */}
        {showViewMore && (
          <div className="reveal mt-12 flex flex-col items-center gap-3">
            <p className="text-sm text-[#5A6485]">
              Showing {displayed.length} of {STATIC_IMAGES.length} photos
            </p>
            <PYCButton asChild variant="primary" size="lg">
              <a href="/gallery">
                <Images className="size-5" />
                View Full Gallery
                <ArrowRight className="size-4" />
              </a>
            </PYCButton>
          </div>
        )}

        {/* Load More button — only on full gallery page with pagination */}
        {hasMore && (
          <div className="reveal mt-12 flex flex-col items-center gap-3">
            <p className="text-sm text-[#5A6485]">
              Showing {displayed.length} of {filtered.length} photos
              {remainingCount > 0 && ` · ${remainingCount} more to load`}
            </p>
            <PYCButton
              variant="outline"
              size="lg"
              onClick={() => setVisibleCount((c) => c + pageSize)}
            >
              <Loader2 className="size-4" />
              Load {Math.min(pageSize, remainingCount)} More Photos
            </PYCButton>
          </div>
        )}

        {/* End-of-gallery indicator */}
        {!isLimited && !hasMore && filtered.length > pageSize && (
          <div className="reveal mt-12 text-center">
            <p className="text-sm text-[#5A6485]">
              You've seen all {filtered.length} photos
            </p>
          </div>
        )}
      </div>

      {/* Lightbox modal */}
      {lightboxIndex !== null && displayed[lightboxIndex] && (
        <div
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/90 backdrop-blur-sm p-4"
          onClick={() => setLightboxIndex(null)}
        >
          {/* Close button */}
          <button
            onClick={() => setLightboxIndex(null)}
            aria-label="Close"
            className="absolute top-4 right-4 z-10 inline-flex size-12 items-center justify-center rounded-full bg-white/10 text-white hover:bg-white/20 transition-colors"
          >
            <X className="size-6" />
          </button>

          {/* Previous button */}
          <button
            onClick={(e) => {
              e.stopPropagation();
              setLightboxIndex((prev) =>
                prev !== null
                  ? (prev - 1 + displayed.length) % displayed.length
                  : null
              );
            }}
            aria-label="Previous image"
            className="absolute left-4 z-10 inline-flex size-12 items-center justify-center rounded-full bg-white/10 text-white hover:bg-white/20 transition-colors md:size-14"
          >
            <ChevronLeft className="size-6 md:size-7" />
          </button>

          {/* Image */}
          <img
            src={displayed[lightboxIndex].src}
            alt={displayed[lightboxIndex].alt}
            className="max-h-[85vh] max-w-[90vw] object-contain rounded-2xl shadow-2xl"
            onClick={(e) => e.stopPropagation()}
          />

          {/* Next button */}
          <button
            onClick={(e) => {
              e.stopPropagation();
              setLightboxIndex((prev) =>
                prev !== null ? (prev + 1) % displayed.length : null
              );
            }}
            aria-label="Next image"
            className="absolute right-4 z-10 inline-flex size-12 items-center justify-center rounded-full bg-white/10 text-white hover:bg-white/20 transition-colors md:size-14"
          >
            <ChevronRight className="size-6 md:size-7" />
          </button>

          {/* Counter */}
          <p className="absolute bottom-4 left-1/2 -translate-x-1/2 rounded-full bg-black/50 px-4 py-1.5 text-sm text-white/80 backdrop-blur">
            {lightboxIndex + 1} / {displayed.length}
          </p>
        </div>
      )}
    </section>
  );
}
