import { NextRequest, NextResponse } from "next/server";
import { writeFile, readFile, mkdirSync, readdirSync, statSync, existsSync } from "fs";
import { join } from "path";
import { promisify } from "util";
import sharp from "sharp";

// Allow longer processing time for bulk uploads
export const maxDuration = 300; // 5 minutes for large batches

const writeFileAsync = promisify(writeFile);
const readFileAsync = promisify(readFile);

const GALLERY_DIR = join(process.cwd(), "public", "gallery");
const MANIFEST_PATH = join(process.cwd(), "src", "data", "gallery-images.ts");
const CATEGORIES = ["community", "education", "health", "environment", "events"];
const VALID_EXTENSIONS = [".jpg", ".jpeg", ".png", ".webp"];

function sanitizeFilename(name: string): string {
  return name
    .toLowerCase()
    .replace(/\.[^.]+$/, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .substring(0, 60);
}

function humanToTitle(slug: string): string {
  return slug
    .replace(/\.[^.]+$/, "")
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function scanCategory(categorySlug: string, publicRoot: string) {
  const dir = join(GALLERY_DIR, categorySlug);
  if (!existsSync(dir)) return [];

  const files = readdirSync(dir).sort();
  const images: Array<{
    src: string;
    alt: string;
    category: string;
    span?: boolean;
  }> = [];

  for (const file of files) {
    const fullPath = join(dir, file);
    const ext = "." + file.split(".").pop()?.toLowerCase();

    if (file.toUpperCase() === "README.MD" || !VALID_EXTENSIONS.includes(ext)) {
      continue;
    }

    const relativePath = fullPath.replace(publicRoot, "");
    images.push({
      src: relativePath,
      alt: humanToTitle(file),
      category: humanToTitle(categorySlug),
      span: images.length === 0,
    });
  }

  return images;
}

function generateManifest(allImages: any[]) {
  return `// Auto-generated by gallery upload API
// Falls back to the default Unsplash collection if no local images are uploaded.
// Do not edit manually — run the scanner to regenerate.

export interface GalleryImage {
  src: string;
  alt: string;
  category: "Community" | "Education" | "Health" | "Environment" | "Events";
  span?: boolean;
}

const localImages: GalleryImage[] = ${JSON.stringify(allImages, null, 2)};

export default localImages;
`;
}

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData();
    const files = formData.getAll("files") as File[];
    const category = (formData.get("category") as string) || "events";

    if (!files || files.length === 0) {
      return NextResponse.json(
        { error: "No files provided" },
        { status: 400 }
      );
    }

    if (!CATEGORIES.includes(category)) {
      return NextResponse.json(
        { error: `Invalid category. Must be one of: ${CATEGORIES.join(", ")}` },
        { status: 400 }
      );
    }

    const categoryDir = join(GALLERY_DIR, category);
    mkdirSync(categoryDir, { recursive: true });

    const publicRoot = join(process.cwd(), "public");
    const processed: Array<{ name: string; path: string; size: number }> = [];
    const existingNames = new Set(readdirSync(categoryDir));

    for (const file of files) {
      const ext = "." + (file.name.split(".").pop()?.toLowerCase() || "jpg");
      if (!VALID_EXTENSIONS.includes(ext)) {
        continue;
      }

      // Generate unique filename
      let sanitizedName = sanitizeFilename(file.name);
      let counter = 1;
      while (existingNames.has(`${sanitizedName}.jpg`)) {
        sanitizedName = `${sanitizeFilename(file.name)}-${counter}`;
        counter++;
      }
      existingNames.add(`${sanitizedName}.jpg`);

      const outPath = join(categoryDir, `${sanitizedName}.jpg`);
      const bytes = await file.arrayBuffer();
      const buffer = Buffer.from(bytes);

      // Optimize: resize to max 1200px wide, progressive JPEG
      await sharp(buffer)
        .resize(1200, null, { withoutEnlargement: true, fit: "inside" })
        .jpeg({ quality: 82, progressive: true, mozjpeg: true })
        .toFile(outPath);

      const stats = statSync(outPath);
      processed.push({
        name: file.name,
        path: `/gallery/${category}/${sanitizedName}.jpg`,
        size: Math.round(stats.size / 1024),
      });
    }

    // Regenerate manifest
    const allImages: any[] = [];
    for (const cat of CATEGORIES) {
      allImages.push(...scanCategory(cat, publicRoot));
    }

    const manifestContent = generateManifest(allImages);
    await writeFileAsync(MANIFEST_PATH, manifestContent, "utf-8");

    return NextResponse.json({
      success: true,
      processed: processed.length,
      images: processed,
      totalGalleryImages: allImages.length,
    });
  } catch (error) {
    console.error("Upload error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Upload failed" },
      { status: 500 }
    );
  }
}

export async function GET() {
  try {
    const publicRoot = join(process.cwd(), "public");
    const allImages: any[] = [];
    for (const cat of CATEGORIES) {
      allImages.push(...scanCategory(cat, publicRoot));
    }

    const counts: Record<string, number> = {};
    for (const cat of CATEGORIES) {
      counts[cat] = allImages.filter((img) => img.category.toLowerCase() === cat).length;
    }

    return NextResponse.json({
      total: allImages.length,
      counts,
    });
  } catch (error) {
    return NextResponse.json(
      { error: "Failed to get gallery stats" },
      { status: 500 }
    );
  }
}
