// Auto-generated by `bun run scripts/scan-gallery.js`
// Falls back to the default Unsplash collection if no local images are uploaded.
// Do not edit manually — run the scanner to regenerate.

export interface GalleryImage {
  src: string;
  alt: string;
  category: "Community" | "Education" | "Health" | "Environment" | "Events";
  span?: boolean;
}

const localImages: GalleryImage[] = [
  {
    "src": "/gallery/events/pyc-panel-discussion.jpg",
    "alt": "Pyc Panel Discussion",
    "category": "Events",
    "span": true
  }
];

export default localImages;
